name: Coverity Buildless Scan
                                                                                                                                                                                                                                         
on:
  push:
    branches: [ main, master, develop, stage, release ]
 
                                                                                                                                                                                                                                         
jobs:
  coverity-buildless-scan:
    runs-on: [mac-arm-sh]
                                                                                                                                                                                                                                         
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

                                                                                                                                                                                                                                         
    - name: Coverity Buildless Scan
      uses: blackduck-inc/black-duck-security-scan@v2
      with:
        coverity_url: ${{ vars.COVERITY_URL }}
        coverity_user: ${{ secrets.COVERITY_USER }}
        coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
      

      
