name: Coverity Buildless Scan
                                                                                                                                                                                                                                         
on:
  push:
    branches: [main, master, develop, stage, release]
  pull_request:
    branches: [main, master, develop, stage, release]

jobs:
  coverity-scan:
    runs-on: [ mac-arm-sh ]
    
    defaults:
      run:
        working-directory: ${{ github.workspace }}/nodejs-npm

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # Specify Node version
   
    - name: Coverity Buildless Scan
      uses: blackduck-inc/black-duck-security-scan@v2
      with:
        coverity_url: ${{ secrets.COVERITY_URL }}
        coverity_user: ${{ secrets.COVERITY_USER }}
        coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
      

      
